schema = 1
name = "Testmod"
modid = "testmod"
version = "1.0.0"
description = "test description"

[[transformations]]
name = "test transform"
targets = ["net.minecraft.client.main.Main"]
specifier = "io.github.testmod.MainTransformation"

[[entrypoints]]
id = "loader_plugin"
specifier = "io.github.testmod.TestLoaderPlugin"

[[entrypoints]]
id = "loader_plugin"
specifier = "test.class.level.Kt::test"

[[entrypoints]]
id = "loader_plugin"
specifier = "test.class.level.Kt::test2"

[[entrypoints]]
id = "loader_plugin"
specifier = "test.class.level.Kt::testC"

[[entrypoints]]
id = "loader_plugin"
specifier = "test.class.level.Kt::testC2"

[[dependencies.requires]]
modid = "felis"
version = ">=1.5.0"

[[dependencies.requires]]
modid = "minecraft"
version = ">=1.20"

[[dependencies.requires]]
modid = "micromixin"
version = ">=1.4.0-alpha"