schema = 1
name = "Felis Loader"
modid = "felis"
version = "${version}"

[description]
description = """
You know how you sometimes need that one loader feature, that is not usable from mods?
You know how no loaders allow you to modify their behavior to a huge extend?
Yea, that's no more thanks to Felis.
"""
slogan = "A modern mod loader for Minecraft"

license = "MIT"

[contact]
issueTracker = "https://github.com/Felis-Project/felis/issues"
sources = "https://github.com/Felis-Project/felis"
homepage = "https://github.com/Felis-Project/"
other = { discord = "https://discord.gg/fsvqcbpEWJ" }

[[people.authors]]
name = "0xJoeMama"

